sonar.projectKey=estudemy_backend
sonar.projectName=Backend API

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info